# Local packages that have no nixpkgs equivalent.
#
# Imported as an overlay in flake.nix:
#   pkgs = import nixpkgs { overlays = [ (import ./pkgs) ]; ... };
#
# Three things live here:
#   quadcast2s   - your own project, built from the checkout on disk
#   reigntweak   - prebuilt binary from the upstream GitHub release
#   cheatengine  - Windows CE binary + a protontricks launcher
#
{ quadcast2sSrc }:
final: prev:
let
  lib = prev.lib;
in
# Scripts are defined in ./scripts.nix. They live in the overlay so that
# modules/services.nix can reference the same store paths.
(import ./scripts.nix final prev)
// (import ./wallpaper-engine.nix final prev)
// {
  # Cherry Studio, pinned from upstream's AppImage by nvfetcher.
  cherry-studio = prev.callPackage ./cherry-studio.nix { };

  # ---------------------------------------------------------------------------
  # quadcast2s — RGB lighting for the HyperX QuadCast 2 S
  #
  # Mirrors packaging/PKGBUILD: the wheel lands in site-packages, then the
  # udev rule, desktop entry, icon and docs are installed alongside.
  #
  # The systemd user units from the repo are installed as reference docs only.
  # They hardcode /usr/bin/quadcast2s, which is meaningless on NixOS — the real
  # units are generated by modules/services.nix with the store path substituted.
  #
  # NOTE: source is a local checkout, not a URL. Once the project has a public
  # git remote, swap `src` for a fetchFromGitHub and this becomes reproducible.
  # ---------------------------------------------------------------------------
  quadcast2s = prev.python3Packages.buildPythonApplication rec {
    pname = "quadcast2s";
    version = "0.2.0";
    pyproject = true;

    # Supplied as a `flake = false` path input from flake.nix, so the source is
    # copied into the store at lock time. Refresh after editing the project:
    #   nix flake lock --update-input quadcast2sSrc
    src = quadcast2sSrc;

    build-system = [ prev.python3Packages.setuptools ];
    # PySide6 is in dependencies rather than an optional extra: both entry
    # points ship from this one derivation and the GUI is what writes
    # ~/.config/quadcast2s/service.env, so the extra is not really optional.
    dependencies = [
      prev.python3Packages.pyusb
      prev.python3Packages.pyside6
    ];

    # Upstream tests want a real microphone on the USB bus.
    doCheck = false;

    # The project checkout carries build artifacts from earlier local builds:
    # dist/ contains a stale quadcast2s-0.1.0 wheel AND a 0.2.0 wheel, and BOTH
    # declare the same entry point --
    #   [console_scripts] quadcast2s = quadcast2s.__main__:main
    # nixpkgs' install phase globs dist/*.whl and installs every wheel present,
    # so bin/quadcast2s is written twice and the installer dies with
    # FileExistsError. Strip the artifacts and build from source.
    #
    # The proper fix is in the project, not here: put dist/, build/ and
    # *.egg-info/ in .gitignore and delete them from the working tree.
    postPatch = ''
      rm -rf dist build src/*.egg-info
    '';

    postInstall = ''
      appid=xyz.coruscnium.quadcast2s

      # Consumed by services.udev.packages on the NixOS side:
      #   services.udev.packages = [ pkgs.quadcast2s ];
      install -Dm644 udev/70-quadcast2s.rules \
        $out/lib/udev/rules.d/70-quadcast2s.rules

      install -Dm644 desktop/$appid.desktop \
        $out/share/applications/$appid.desktop
      install -Dm644 desktop/$appid.metainfo.xml \
        $out/share/metainfo/$appid.metainfo.xml
      install -Dm644 desktop/quadcast2s.svg \
        $out/share/icons/hicolor/scalable/apps/quadcast2s.svg

      install -Dm644 LICENSE $out/share/licenses/$pname/LICENSE
      install -Dm644 README.md $out/share/doc/$pname/README.md
      for doc in docs/*.md; do
        install -Dm644 "$doc" $out/share/doc/$pname/$(basename "$doc")
      done

      # Reference copies only — see the note above.
      install -Dm644 systemd/quadcast2s.service \
        $out/share/doc/$pname/quadcast2s.service
      install -Dm644 systemd/quadcast2s-hotplug.service \
        $out/share/doc/$pname/quadcast2s-hotplug.service
    '';

    meta = {
      description = "RGB lighting control for the HyperX QuadCast 2 S microphone";
      homepage = "https://github.com/Coruscnium/quadcast2s";
      license = lib.licenses.agpl3Only;
      mainProgram = "quadcast2s";
      platforms = lib.platforms.linux;
    };
  };

  # ---------------------------------------------------------------------------
  # reigntweak — Elden Ring: Nightreign ultrawide / 60 FPS patcher
  #
  # Upstream ships a bare x86_64 binary and no source. The hash below is the
  # one GitHub reports for the Release1.2 asset, and it matches the copy that
  # was already sitting in ~/.local/bin, so this is the same build.
  # ---------------------------------------------------------------------------
  reigntweak = prev.stdenvNoCC.mkDerivation rec {
    pname = "reigntweak";
    version = "1.2";

    src = prev.fetchurl {
      url = "https://github.com/Minksh/ReignTweak/releases/download/Release1.2/reigntweak";
      hash = "sha256-WOQMLqi+TCE7kECA2UbzcFv6KcqOByzTkJJwRiMIm+s=";
    };

    dontUnpack = true;
    nativeBuildInputs = [ prev.autoPatchelfHook ];
    buildInputs = [ prev.stdenv.cc.cc.lib ];

    installPhase = ''
      runHook preInstall
      install -Dm755 $src $out/bin/reigntweak
      runHook postInstall
    '';

    meta = {
      description = "Ultrawide and 60 FPS patcher for Elden Ring: Nightreign";
      homepage = "https://github.com/Minksh/ReignTweak";
      license = lib.licenses.unfree; # no license declared upstream
      platforms = [ "x86_64-linux" ];
    };
  };

  # ---------------------------------------------------------------------------
  # Cheat Engine — Windows build, run inside a game's Proton prefix.
  #
  # There is no cheat-engine package in nixpkgs, and the upstream GitHub
  # releases carry no assets (the installer only lives on cheatengine.org), so
  # the binary is vendored from the existing local copy.
  #
  # This replaces BOTH cehelper.sh and the third-party "Proton.SH by NuLLxD"
  # script: protontricks-launch already finds the right prefix for an appid.
  # ---------------------------------------------------------------------------
  cheatengine = prev.stdenvNoCC.mkDerivation rec {
    pname = "cheatengine";
    version = "7.5"; # TODO confirm against the vendored binary

    # Vendored into this flake directory: upstream GitHub releases carry no
    # assets and cheatengine.org has no stable URL, so there is nothing to
    # fetch. Pure eval forbids reading it from ~/.local/bin.
    src = ./cheatengine-x86_64.exe;

    dontUnpack = true;
    dontPatchELF = true;

    installPhase = ''
      runHook preInstall
      install -Dm644 $src $out/share/cheatengine/cheatengine-x86_64.exe
      runHook postInstall
    '';

    meta = {
      description = "Cheat Engine (Windows build) for use under Proton";
      homepage = "https://cheatengine.org";
      license = lib.licenses.gpl2Plus;
      platforms = [ "x86_64-linux" ];
    };
  };

  # Thin launcher: cheatengine <steam-appid> [args...]
  cheatengine-launcher = prev.writeShellApplication {
    name = "cheatengine";
    runtimeInputs = [ prev.protontricks ];
    text = ''
      if [ "$#" -lt 1 ]; then
        echo "usage: cheatengine <steam-appid> [CE args...]" >&2
        echo "  e.g. cheatengine 1245620   # ELDEN RING" >&2
        exit 2
      fi
      appid="$1"
      shift
      exec protontricks-launch --appid "$appid" \
        ${final.cheatengine}/share/cheatengine/cheatengine-x86_64.exe "$@"
    '';
  };

}
