# Local packages that have no nixpkgs equivalent.
#
# Imported as an overlay in flake.nix:
#   pkgs = import nixpkgs { overlays = [ (import ./pkgs) ]; ... };
#
# Two things live here:
#   quadcast2s   - your own project, built from the checkout on disk
#   reigntweak   - Elden Ring: Nightreign patcher, built from source
#
{ quadcast2sSrc }:
final: prev:
let
  lib = prev.lib;

  # See the `mangohud` override below. nixpkgs' glfw is 3.4; this pins 3.3.10.
  glfw33 = prev.glfw.overrideAttrs (o: {
    version = "3.3.10";
    src = prev.fetchFromGitHub {
      owner = "glfw";
      repo = "GLFW";
      rev = "3.3.10";
      hash = "sha256-kTRXsfQ+9PFurG3ffz0lwnITAYAXtNl3h/3O6FSny5o=";
    };
    # nixpkgs' postPatch rewrites Wayland dlopen paths in src/wl_init.c, a file
    # the 3.3.x tree does not have. 3.3.x builds X11-only anyway.
    postPatch = "";
  });
in
# Scripts are defined in ./scripts.nix. They live in the overlay so that
# modules/services.nix can reference the same store paths.
(import ./scripts.nix final prev)
// (import ./wallpaper-engine.nix final prev)
// {
  # Cherry Studio, pinned from upstream's AppImage by nvfetcher.
  cherry-studio = prev.callPackage ./cherry-studio.nix { pkgs = prev; };

  # BeautySolar icons. nixpkgs has BeautyLine (beauty-line-icon-theme) but not
  # this sibling, and theming.nix asks for it by name.
  beautysolar = prev.callPackage ./beautysolar.nix { };

  # The Carl suite as a system-wide package. Needed because the Plasma Login
  # Manager greeter runs as its own user and cannot see coru's home, where
  # modules/theming.nix otherwise installs these. themesDir is the vendored
  # tree, so the greeter and the session share one source of truth.
  carl-theme = prev.callPackage ./carl-theme.nix { themesDir = ../themes; };

  # ---------------------------------------------------------------------------
  # quadcast2s — RGB lighting for the HyperX QuadCast 2 S
  #
  # Mirrors packaging/PKGBUILD: the wheel lands in site-packages, then the
  # udev rule, desktop entry, icon and docs are installed alongside.
  #
  # The systemd user units from the repo are installed as reference docs only.
  # They hardcode /usr/bin/quadcast2s, which is meaningless on NixOS — the real
  # units are generated by modules/services.nix with the store path substituted.
  #
  # NOTE: source is a local checkout, not a URL. Once the project has a public
  # git remote, swap `src` for a fetchFromGitHub and this becomes reproducible.
  # ---------------------------------------------------------------------------
  quadcast2s = prev.python3Packages.buildPythonApplication rec {
    pname = "quadcast2s";
    version = "0.2.0";
    pyproject = true;

    # Supplied as a path argument from flake.nix (./vendor/quadcast2s), so the
    # source is copied into the store at build time. Editing the vendored tree is
    # picked up on the next build -- no lock update needed.
    src = quadcast2sSrc;

    build-system = [ prev.python3Packages.setuptools ];
    # PySide6 is in dependencies rather than an optional extra: both entry
    # points ship from this one derivation and the GUI is what writes
    # ~/.config/quadcast2s/service.env, so the extra is not really optional.
    dependencies = [
      prev.python3Packages.pyusb
      prev.python3Packages.pyside6
    ];

    # Upstream tests want a real microphone on the USB bus.
    doCheck = false;

    # The project checkout carries build artifacts from earlier local builds:
    # dist/ contains a stale quadcast2s-0.1.0 wheel AND a 0.2.0 wheel, and BOTH
    # declare the same entry point --
    #   [console_scripts] quadcast2s = quadcast2s.__main__:main
    # nixpkgs' install phase globs dist/*.whl and installs every wheel present,
    # so bin/quadcast2s is written twice and the installer dies with
    # FileExistsError. Strip the artifacts and build from source.
    #
    # The proper fix is in the project, not here: put dist/, build/ and
    # *.egg-info/ in .gitignore and delete them from the working tree.
    postPatch = ''
      rm -rf dist build src/*.egg-info
    '';

    postInstall = ''
      appid=xyz.coruscnium.quadcast2s

      # Consumed by services.udev.packages on the NixOS side:
      #   services.udev.packages = [ pkgs.quadcast2s ];
      install -Dm644 udev/70-quadcast2s.rules \
        $out/lib/udev/rules.d/70-quadcast2s.rules

      install -Dm644 desktop/$appid.desktop \
        $out/share/applications/$appid.desktop
      install -Dm644 desktop/$appid.metainfo.xml \
        $out/share/metainfo/$appid.metainfo.xml
      install -Dm644 desktop/quadcast2s.svg \
        $out/share/icons/hicolor/scalable/apps/quadcast2s.svg

      install -Dm644 LICENSE $out/share/licenses/$pname/LICENSE
      install -Dm644 README.md $out/share/doc/$pname/README.md
      for doc in docs/*.md; do
        install -Dm644 "$doc" $out/share/doc/$pname/$(basename "$doc")
      done

      # Reference copies only — see the note above.
      install -Dm644 systemd/quadcast2s.service \
        $out/share/doc/$pname/quadcast2s.service
      install -Dm644 systemd/quadcast2s-hotplug.service \
        $out/share/doc/$pname/quadcast2s-hotplug.service
    '';

    meta = {
      description = "RGB lighting control for the HyperX QuadCast 2 S microphone";
      homepage = "https://github.com/Coruscnium/quadcast2s";
      license = lib.licenses.agpl3Only;
      mainProgram = "quadcast2s";
      platforms = lib.platforms.linux;
    };
  };

  # ---------------------------------------------------------------------------
  # reigntweak — Elden Ring: Nightreign ultrawide / 60 FPS patcher
  #
  # Built from source: plain C++17 against the standard library plus pthread, no
  # external deps. Upstream also ships a prebuilt binary, but building it here
  # means the compiler and the resulting binary are ours, not a downloaded blob.
  # The build command mirrors build.sh in the repo.
  # ---------------------------------------------------------------------------
  reigntweak = prev.stdenv.mkDerivation {
    pname = "reigntweak";
    version = "unstable-2026-04-18";

    src = prev.fetchFromGitHub {
      owner = "Minksh";
      repo = "ReignTweak";
      rev = "6f999c4f5c2483bed73c2cce715ebeee4a721d8a";
      hash = "sha256-Lt8++TRIFnsG6h5PDNwBqTIPAePaYV2mTCSukdjZcjY=";
    };

    buildPhase = ''
      runHook preBuild
      $CXX -std=c++17 reigntweak.cpp fps_patch.cpp ultrawide_patch.cpp \
        depth_buffer_patch.cpp -o reigntweak -lpthread
      runHook postBuild
    '';

    installPhase = ''
      runHook preInstall
      install -Dm755 reigntweak $out/bin/reigntweak
      runHook postInstall
    '';

    meta = {
      description = "Ultrawide and 60 FPS patcher for Elden Ring: Nightreign";
      homepage = "https://github.com/Minksh/ReignTweak";
      license = lib.licenses.unfree; # no license declared upstream
      platforms = [ "x86_64-linux" ];
    };
  };

  # ---------------------------------------------------------------------------
  # mangohud — pinned to glfw 3.3.10 because mangoapp segfaults on glfw 3.4.
  #
  # gamescope's `--mangoapp` spawns the separate `mangoapp` binary. Against
  # nixpkgs' glfw 3.4 (built with both the Wayland and X11 backends) mangoapp's
  # X11 init fails -- "Glfw Error 65550: X11: Platform not initialized" -- and it
  # then calls XInternAtom on the null display and dumps core (SIGSEGV), so the
  # HUD never shows, inside gamescope or out. Upstream flightlessmango/MangoHud
  # #1261 names glfw 3.3.10 (X11-only) as the fix. Verified here: the 3.3.10
  # build runs instead of crashing.
  #
  # Overriding mangohud (not glfw globally) keeps every other glfw consumer on
  # 3.4. Both consumers of mangohud pick this up: home-manager's
  # programs.mangohud and programs.steam.extraPackages.
  # ---------------------------------------------------------------------------
  mangohud = prev.mangohud.override { glfw = glfw33; };

}
