# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  cherry-studio = {
    pname = "cherry-studio";
    version = "2.1.4";
    src = fetchurl {
      url = "https://github.com/CherryHQ/cherry-studio/releases/download/v2.1.4/Cherry-Studio-2.1.4-linux-x64.AppImage";
      name = "Cherry-Studio-2.1.4-linux-x64.AppImage";
      sha256 = "sha256-A8fKKhg+ODiTMMvWHyJu1WhcJ0hR+VFFCGGbqWFzMbs=";
    };
  };
  elegooslicer = {
    pname = "elegooslicer";
    version = "1.5.3.5";
    src = fetchurl {
      url = "https://github.com/elegooofficial/ElegooSlicer/releases/download/v1.5.3.5/ElegooSlicer_Linux_V1.5.3.5.AppImage";
      name = "ElegooSlicer_Linux_V1.5.3.5.AppImage";
      sha256 = "sha256-ezs/CODQ1Ru0cshYZdG+mwwoOFQj2rocsMOyJdAQGvw=";
    };
  };
}
