# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  cherry-studio = {
    pname = "cherry-studio";
    version = "2.1.4";
    src = fetchurl {
      url = "https://github.com/CherryHQ/cherry-studio/releases/download/v2.1.4/Cherry-Studio-2.1.4-linux-x64.AppImage";
      name = "Cherry-Studio-2.1.4-linux-x64.AppImage";
      sha256 = "sha256-A8fKKhg+ODiTMMvWHyJu1WhcJ0hR+VFFCGGbqWFzMbs=";
    };
  };
}
